development:
  secret_key_base: 90267979852fe0324d0b213165cb087d683522cee042ec281120117551b1c0054f576f85cefe3775e08035e64cb4f3f52dcabdf44d8d923ea2ba1e099c07c6e9
  coolpay:
    username: <%= ENV["COOLPAY_USERNAME"] %>
    api_key:  <%= ENV["COOLPAY_API_KEY"] %>
    host:     <%= ENV["COOLPAY_HOST"] %>

test:
  secret_key_base: e011e9081b5b82d36e7d95854f10a4b54bea8abb924391ff990cd5aa191ed8f744d499bb2631672db28bb84304149b008e7d4a8a0dc91ef91642c421ece190ed
  coolpay:
    username: fake_username
    api_key:  fake_api_key
    host:     fake_host

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  coolpay:
    username: <%= ENV["COOLPAY_USERNAME"] %>
    api_key:  <%= ENV["COOLPAY_API_KEY"] %>
    host:     <%= ENV["COOLPAY_HOST"] %>
